らんだむをかえたよ
NamagomiNetwork/Namagomi-bot pull request #150
Opened 2024-04-26 02:51 UTC by ikazuchizero

従来のrandomをrandom-numに変更
回数の指定が必要ないrandomを作成
やる気元気無敵だって金曜日だもん

2024-04-26 02:52 UTC, ikazuchizero commented
@kuroma6666 @yuuki1293

2024-04-26 02:58 UTC, kuroma6666 approved these changes
よさそう

2024-04-26 03:01 UTC, ikazuchizero commented
おそろしくはやいレビュー

2024-04-26 03:22 UTC, yuuki1293 commented
リポジトリのルートにソースコードを置くな高校

2024-04-26 03:23 UTC, kuroma6666 commented
ホントだ草（ソースのロジックしか見てなかった）

2024-04-26 03:32 UTC, kuroma6666 requested changes

2024-04-26 03:32 UTC, kuroma6666 commented on help-embed.js
```
    {
      name: "`random [選択肢1] [選択肢2] ● ● ●`",
      value: "抽選を行います",
    },
    {
      name: "`random-num [試行回数] [選択肢1] [選択肢2] ● ● ●`",
      value: "任意の回数抽選を行います",
    },
```
を`src/commands/utils/help-embed.js`にマージで良いかな

2024-04-26 03:32 UTC, kuroma6666 commented on random-num.js
これは`src/commands`に移動してください

2024-04-26 03:32 UTC, kuroma6666 commented on random.js
これは`src/commands`に移動してください、`random.js`を上書きするような感じで良いと思います

2024-04-26 04:35 UTC, ikazuchizero commented
明らかにバカで草

2024-04-27 02:19 UTC, ikazuchizero commented
@kuroma6666 @yuuki1293 
ど？

2024-04-27 02:27 UTC, yuuki1293 approved these changes
よさそう

2024-04-27 03:25 UTC, kuroma6666 commented
@ikazuchizero 
ルートディレクトリにhelp-embed.jsが残留してるので、削除してコミットすれば後は良さそうです

2024-04-27 03:38 UTC, ikazuchizero commented
けした

2024-04-27 03:43 UTC, kuroma6666 approved these changes
あぷろーぶ

2024-04-28 04:13 UTC, ikazuchizero commented
じゃあええか

2024-04-28 04:13 UTC, merged