feat:version-cmdのCommit情報追加
NamagomiNetwork/Namagomi-bot pull request #55
Opened 2023-07-23 01:12 UTC by kuroma6666

- Commit情報の取得方法変更
 - hashとmessageも取得する
- embedのfields追加
 - commit messageを出力する為

2023-07-23 01:18 UTC, kuroma6666 commented
ミスった...🙇‍♂️
![image](https://github.com/NamagomiNetwork/Namagomi-bot/assets/48423435/89958044-4382-417b-b5d9-5fd8f22831e6)

2023-08-05 04:44 UTC, kuroma6666 commented
[memo]
本PR上でのCommitでhttps://github.com/NamagomiNetwork/Namagomi-bot/pull/55/commits/b01b2bf4cc16b1a8eb4a973d750245c3ac0a99ac はrevertし、
別PR（formatteかけるだけ）に切り出しを行う

2023-08-06 09:02 UTC, kuroma6666 commented
@ikazuchizero ,@yuuki1293
Review指摘お願いしまーす

2023-08-07 03:03 UTC, yuuki1293 requested changes

2023-08-07 03:03 UTC, yuuki1293 commented on src/commands/version.js
> +        return;
returnしたら取得できなかった場合に何も送信されない

2023-08-07 03:03 UTC, yuuki1293 commented on src/commands/version.js
> +      var embed = new MessageEmbed({
`embed`は`const`にできます

2023-08-07 03:33 UTC, kuroma6666 commented on src/commands/version.js
> +      var embed = new MessageEmbed({
これは別PRに切り出すべき話ではあるが…）embed(MessageEmbed)がconstでないのも修正した方が良さそうね

2023-08-08 14:32 UTC, kuroma6666 commented
@yuuki1293 再確認おなしゃす

2023-08-09 04:11 UTC, yuuki1293 approved these changes
よさそう

2023-08-12 12:54 UTC, kuroma6666 commented
イメージも一応貼っとく
![image](https://github.com/NamagomiNetwork/Namagomi-bot/assets/48423435/e642fa58-4338-4769-a1ca-7d398e46a2c8)

2023-08-12 14:41 UTC, ikazuchizero commented
BLT

2023-08-18 14:38 UTC, kuroma6666 commented
@ikazuchizero 
適当な時にMergeしといてください～

2023-08-18 16:12 UTC, merged